# Generated by Django 3.2.6 on 2022-06-14 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('presensi', '0002_alter_pegawai_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presensi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('masuk', models.TimeField()),
                ('pulang', models.TimeField()),
                ('suhu', models.CharField(max_length=5)),
                ('keterangan', models.CharField(max_length=100)),
                ('pegawai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presensi.pegawai')),
            ],
        ),
    ]
