# Generated by Django 3.2.6 on 2022-06-13 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelWajah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.FileField(upload_to='media/model')),
                ('total_data', models.CharField(max_length=4)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
