# Generated by Django 3.2.6 on 2022-06-22 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facerec', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelwajah',
            name='nama',
            field=models.FileField(upload_to='media/model/'),
        ),
    ]
